# cargo

# [[file:~/Workspace/Programming/gchemol-rs/lattice/lattice.note::*cargo][cargo:1]]
[package]
name = "lattice"
version = "0.0.4"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
serde = {version="1", features = ["derive"]}
vecfx = { version="0.0.8", features = ["nalgebra"] }
gchemol-gut = "0.0.7"

[dev-dependencies]
approx = { version = "0.3" }

[features]
# for adhoc hacking
adhoc = []
# cargo:1 ends here
