# cargo

# [[file:~/Workspace/Programming/gchemol-rs/lattice/lattice.note::*cargo][cargo:1]]
[package]
name = "gchemol_lattice"
version = "0.0.2"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
serde = {version="1", features = ["derive"]}
vecfx = { git = "https://github.com/gchemol/vecfx.git", features = ["nalgebra"] }
guts = { git = "https://github.com/ybyygu/guts.git" }

[dev-dependencies]
approx = { version = "0.3" }
# cargo:1 ends here
